"""
Conversation history management for Iris v3
In-memory representation of recent conversation loaded from database
"""

from typing import List, Dict, Optional
import os
import sys
import re
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.insert(0, PROJECT_ROOT)
from app import config
from database import persistence
from core import attachments


class ConversationHistory:
    """Manages conversation history with database persistence"""
    
    def __init__(self, enable_persistence: bool = True):
        """
        Initialize conversation history
        
        Loads recent conversation from database (across all sessions!)
        
        Args:
            enable_persistence: If True, save/load from database
        """
        self.messages: List[Dict[str, str]] = []
        self.enable_persistence = enable_persistence
        
        if enable_persistence:
            # Get/create session (for analytics, not for loading!)
            self.session_id = persistence.get_or_create_session()
            
            # Load recent conversation (ACROSS ALL SESSIONS!)
            self.messages = persistence.load_recent_conversation()
            
            if self.messages:
                print(f"[conversation.py][__init__] ✓ Loaded {len(self.messages)} messages into working memory")
            else:
                print(f"[conversation.py][__init__] ✓ Starting fresh conversation")
        else:
            self.session_id = None
            print(f"[conversation.py][__init__] In-memory only (no persistence)")
    
    def add_user_message(self, content: str, images: Optional[List[str]] = None, sender: str = 'user') -> None:
        """
        Add a user message to history

        Args:
            content: Message text
            images: Optional list of base64-encoded images (with or without data URI)
            sender: Message sender identifier ('user' for Victor, 'claude_code' for Claude, etc.)
        """
        msg = {
            "role": "user",
            "content": content
        }

        # Handle image attachments
        attachment_metadata = []
        if images and self.session_id:
            print(f"[conversation.py][add_user_message] Processing {len(images)} image(s)...")
            for idx, image_base64 in enumerate(images):
                try:
                    # Save image to disk and get metadata
                    metadata = attachments.save_base64_image(
                        session_id=self.session_id,
                        base64_string=image_base64,
                        is_user_upload=True,
                        filename=f"user_upload_{idx}.png"
                    )
                    attachment_metadata.append(metadata)
                    print(f"[conversation.py][add_user_message]   ✓ Saved image {idx+1}: {metadata['path']}")
                except Exception as e:
                    print(f"[conversation.py][add_user_message]   ✗ Error saving image {idx+1}: {e}")

            # Add attachment info to message for in-memory storage
            if attachment_metadata:
                msg["attachments"] = attachments.serialize_attachments(attachment_metadata)

        # Add message to in-memory conversation
        self.messages.append(msg)

        image_info = f" with {len(images)} image(s)" if images else ""
        print(f"[conversation.py][add_user_message] ✓ Added user message ({len(content)} chars{image_info})")

        # Save to database
        if self.enable_persistence and self.session_id:
            persistence.save_message(
                self.session_id,
                "user",
                content,
                attachments=attachment_metadata if attachment_metadata else None,
                sender=sender
            )
    
    def add_assistant_message(self, content: str, tool_calls=None, images: Optional[List[str]] = None, sender: str = 'assistant') -> None:
        """
        Add an assistant message to history

        Args:
            content: Message text
            tool_calls: Optional tool calls JSONB
            images: Optional list of base64-encoded images (generated by tools)
            sender: Message sender identifier (default 'assistant' for Iris)
        """
        msg = {
            "role": "assistant",
            "content": content
        }

        if tool_calls:
            msg["tool_calls"] = tool_calls

        # Handle generated image attachments
        attachment_metadata = []
        if images and self.session_id:
            print(f"[conversation.py][add_assistant_message] Processing {len(images)} generated image(s)...")
            for idx, image_base64 in enumerate(images):
                try:
                    metadata = attachments.save_base64_image(
                        session_id=self.session_id,
                        base64_string=image_base64,
                        is_user_upload=False,  # This is generated content
                        filename=f"generated_{idx}.png"
                    )
                    attachment_metadata.append(metadata)
                    print(f"[conversation.py][add_assistant_message]   ✓ Saved generated image {idx+1}: {metadata['path']}")
                except Exception as e:
                    print(f"[conversation.py][add_assistant_message]   ✗ Error saving image {idx+1}: {e}")

            if attachment_metadata:
                msg["attachments"] = attachments.serialize_attachments(attachment_metadata)

        self.messages.append(msg)

        image_info = f" with {len(images)} image(s)" if images else ""
        print(f"[conversation.py][add_assistant_message] ✓ Added assistant message ({len(content)} chars{image_info})")

        if self.enable_persistence and self.session_id:
            persistence.save_message(
                self.session_id,
                "assistant",
                content,
                tool_calls=tool_calls,
                attachments=attachment_metadata if attachment_metadata else None,
                sender=sender
            )
    
    def add_tool_message(self, content: str, tool_name: str, tool_call_id: str = None, images: Optional[List[str]] = None) -> None:
        """
        Add a tool result message to history

        Args:
            content: Tool result text
            tool_name: Name of tool that was called
            tool_call_id: Optional call ID for correlation
            images: Optional list of base64-encoded images (tool outputs like ComfyUI)
        """
        msg = {
            "role": "tool",
            "content": content,
            "tool_name": tool_name
        }

        if tool_call_id:
            msg["tool_call_id"] = tool_call_id

        # Handle tool-generated image attachments (e.g., ComfyUI output)
        attachment_metadata = []
        if images and self.session_id:
            print(f"[conversation.py][add_tool_message] Processing {len(images)} tool output image(s)...")
            for idx, image_base64 in enumerate(images):
                try:
                    metadata = attachments.save_base64_image(
                        session_id=self.session_id,
                        base64_string=image_base64,
                        is_user_upload=False,
                        filename=f"{tool_name}_{idx}.png"
                    )
                    attachment_metadata.append(metadata)
                    print(f"[conversation.py][add_tool_message]   ✓ Saved {tool_name} output {idx+1}: {metadata['path']}")
                except Exception as e:
                    print(f"[conversation.py][add_tool_message]   ✗ Error saving image {idx+1}: {e}")

            if attachment_metadata:
                msg["attachments"] = attachments.serialize_attachments(attachment_metadata)

        self.messages.append(msg)

        image_info = f" with {len(images)} image(s)" if images else ""
        print(f"[conversation.py][add_tool_message] ✓ Added tool message from {tool_name} ({len(content)} chars{image_info}) \n {content}")

        if self.enable_persistence and self.session_id:
            persistence.save_message(
                self.session_id,
                "tool",
                content,
                tool_call_id=tool_call_id,
                tool_name=tool_name,
                attachments=attachment_metadata if attachment_metadata else None
            )
    
    def get_messages(self) -> List[Dict[str, str]]:
        """Get all messages in working memory"""
        return self.messages.copy()
    
    def reload_from_database(self) -> None:
        """Reload conversation history from database"""
        if self.enable_persistence:
            self.messages = persistence.load_recent_conversation()
            print(f"[conversation.py][reload_from_database] ✓ Reloaded {len(self.messages)} messages")
    
    def get_message_count(self) -> int:
        """Get number of messages in working memory"""
        return len(self.messages)
    
    def get_session_id(self) -> Optional[str]:
        """Get current session ID (for analytics only)"""
        return self.session_id